name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 16
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 16
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Get current date
        id: date
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Build mod jar
        run: ./gradlew deploy
      - name: Upload built jar file
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Olupis but its a jar
          path: build/libs/Olupis-${{ steps.date.outputs.date }}.jar
