name: Java CI

on: [push, pull_request]

jobs:
  buildJar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.2" >> $GITHUB_PATH

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'termuin'
          java-version: '18.0.2'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew deploy

      - name: Upload built jar file
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Olupis-but-a-jar.jar
          path: build/libs/Olupis-but-a-jar.jar
